version: '3'

networks:
    laravel:

services: 
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports: 
            - "8080:80" # Laravel App will run at port 8080
        volumes: 
            - ./src:/var/www # the src is the title of your laravel project folder
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel
    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306" # mysql port
        environment: 
            MYSQL_DATABASE: YOUR_DATABASE_NAME
            MYSQL_USER: YOUR_PREFERRED_MYSQL_USER
            MYSQL_PASSWORD: YOUR_PREFERRED PASSWORD
            MYSQL_ROOT_PASSWORD: YOUR_PREFERRED
            SERVICE_TAGS: dev
            SERVIVE_NAME: mysql # This service name will be referenced in your .env file for database
        networks: 
            - laravel
    
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017" # Mongo Port
        networks: 
            - laravel
    
    redis:
        container_name: redis
        image: redis
        ports: 
            - "6379:6379" # Redis Port
        networks: 
            - laravel
        
    php:
        build: 
            context: .
            dockerfile: Dockerfile # Dockerfile for the build
        container_name: php
        volumes: 
            - ./src:/var/www # the src is the title of your laravel project folder
        ports: 
            - "9000:9000" # PHP Port
        networks: 
            - laravel